thread-safety; logging ratelimit; -t parallel; avoid heap fragmentation; use std::unique_ptr; build updates
 when creating parity files, the main packet was not always being
written to the parity files when they were processed concurrently
because the main packet was not being safely appended to the list of
packets to output because a non-thread-safe data container was being
used. This bug would manifest when a large number of source files were
being processed. Fixed by using a thread-safe data container.

 when creating parity files, the "Opening: <file>" messages will only
be displayed for the first n source files, where n defaults to 200.
This restriction was added so that creating parity files for a large
number of source files would not cause a lot of scrolling which in
turn would make the processing take a long time. Use the new -z<n>
command line switch to set a different limit. Use -z0 to specify no
limit.

 verification of extra files is now performed concurrently if
requested to do so (previously they were always verified serially)

 the -t parameter can now include a positive integer value to restrict
the logical number of CPUs with which to process data with.

 in the Windows version, the program's CPU scheduling priority can now
be specified using the -p parameter

 the heap became fragmented during the verification of data files
because the checksum data buffer was allocated and deallocated for
each file verified, which resulted in the program's memory footprint
(aka its "working set") steadily increasing during the verification
phase. This would result in the 32-bit Windows version failing to
verify large data sets because it could not allocate verification data
buffers. To solve this, the checksum data buffer is no longer
allocated and deallocated for each file verified. Instead, a pool of
checksum objects is created and that pool of objects is then used and
re-used for verifying data files. The size of the pool matches the
number of logical CPUs which the program is asked to use. This change
benefits all versions of the program because by reducing heap
fragmentation, larger data sets can be processed using less virtual
memory.

 numerous small code changes were made to remove unnecessary string
copying. Such redundant copying would further fragment the heap as
well as use up memory for temporary strings which did not need to be
allocated in the first place.

 updated to Intel TBB 4.3 Update 1

 removed use of MAX_PATH or other fixed-size path buffers to avoid
buffer overflow errors

 the program failed to build under newer C++ standard libraries
because they no longer provide std::auto_ptr<T>. Fixed by either using
std::unique_ptr<T> (if available) or by providing our own version of
std::auto_ptr<T>.

(importer's note: GNU C++ provides auto_ptr<T> (deprecated), but not
std::auto_ptr.)

 the 32-bit Mac OS X version now requires 10.5 or later

 stopped building the FreeBSD version because the FreeBSD ports system
can now build the par2 program and TBB library without requiring any
changes to the sources of either and because it isn't possible to
build a "portable" version of the program, in the sense that the TBB
library cannot be in the same directory as the par2 executable - it
must be installed into /usr/lib/, and that is a job best left to the
FreeBSD ports system.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -731,6 +731,7 @@ CPP
 GREP
 EGREP
 LIBOBJS
+PAR2_CXXFLAGS
 LTLIBOBJS'
 ac_subst_files=''
       ac_precious_vars='build_alias
@@ -5264,7 +5265,7 @@ if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
 else
   ac_cv_header_stdc=no
 fi
-rm -f conftest*
+rm -f -r conftest*
 
 fi
 
@@ -5285,7 +5286,7 @@ if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
 else
   ac_cv_header_stdc=no
 fi
-rm -f conftest*
+rm -f -r conftest*
 
 fi
 
@@ -5693,7 +5694,7 @@ if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
 else
   ac_cv_header_stdc=no
 fi
-rm -f conftest*
+rm -f -r conftest*
 
 fi
 
@@ -5714,7 +5715,7 @@ if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
 else
   ac_cv_header_stdc=no
 fi
-rm -f conftest*
+rm -f -r conftest*
 
 fi
 
@@ -6792,7 +6793,7 @@ cat >>confdefs.h <<_ACEOF
 _ACEOF
 ;;
 esac
-rm -f conftest*
+rm -f -r conftest*
   if test $ac_cv_sys_file_offset_bits = unknown; then
     { echo "$as_me:$LINENO: checking for _LARGE_FILES value needed for large files" >&5
 echo $ECHO_N "checking for _LARGE_FILES value needed for large files... $ECHO_C" >&6; }
@@ -6913,7 +6914,7 @@ cat >>confdefs.h <<_ACEOF
 _ACEOF
 ;;
 esac
-rm -f conftest*
+rm -f -r conftest*
   fi
 fi
 
@@ -7024,7 +7025,7 @@ cat >>confdefs.h <<_ACEOF
 _ACEOF
 ;;
 esac
-rm -f conftest*
+rm -f -r conftest*
 
 # We used to try defining _XOPEN_SOURCE=500 too, to work around a bug
 # in glibc 2.1.3, but that breaks too many other things.
@@ -7509,6 +7510,145 @@ _ACEOF
 fi
 done
 
+
+{ echo "$as_me:$LINENO: checking for std::unique_ptr<T> or std::auto_ptr<T>" >&5
+echo $ECHO_N "checking for std::unique_ptr<T> or std::auto_ptr<T>... $ECHO_C" >&6; }
+std_smart_ptr=no
+ac_ext=cpp
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+
+SAVED_CXXFLAGS="${CXXFLAGS}"
+CXXFLAGS="${CXXFLAGS} -std=c++11"
+ac_ext=cpp
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <memory>
+                   #include <vector>
+int
+main ()
+{
+const std::unique_ptr< std::vector<int> > up;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_STD_UNIQUE_PTR 1
+_ACEOF
+ std_smart_ptr='found.std::unique_ptr<T>'
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+CXXFLAGS="${SAVED_CXXFLAGS}"
+ac_ext=cpp
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+
+if test $std_smart_ptr = no; then
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <memory>
+                     #include <vector>
+int
+main ()
+{
+const std::auto_ptr< std::vector<int> > ap;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_STD_AUTO_PTR 1
+_ACEOF
+ std_smart_ptr='found.std::auto_ptr<T>'
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+
+ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+{ echo "$as_me:$LINENO: result: $std_smart_ptr" >&5
+echo "${ECHO_T}$std_smart_ptr" >&6; }
+
+if test $std_smart_ptr = 'found.std::unique_ptr<T>'; then
+  PAR2_CXXFLAGS=-std=c++11
+
+else
+  PAR2_CXXFLAGS=''
+
+fi
 
 ac_config_files="$ac_config_files stamp-h"
 
@@ -8650,10 +8790,11 @@ CPP!$CPP$ac_delim
 GREP!$GREP$ac_delim
 EGREP!$EGREP$ac_delim
 LIBOBJS!$LIBOBJS$ac_delim
+PAR2_CXXFLAGS!$PAR2_CXXFLAGS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 20; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 21; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
@@ -9020,7 +9161,7 @@ do
     cat >>$CONFIG_STATUS <<_ACEOF
     # First, check the format of the line:
     cat >"\$tmp/defines.sed" <<\\CEOF
-/^[	 ]*#[	 ]*undef[	 ][	 ]*$ac_word_re[	 ]*\$/b def
+/^[	 ]*#[	 ]*undef[	 ][	 ]*$ac_word_re[	 ]*/b def
 /^[	 ]*#[	 ]*define[	 ][	 ]*$ac_word_re[(	 ]/b def
 b
 :def
