CUDA; async I/O bugfix for small file writes; use / as path sep even on windows
 fixed a bug which affected the Linux and Mac versions whereby repairs
would fail if the file being repaired was short or had one or two bad
blocks (because the async write to the file's last byte was failing).

 on Windows, the program now stores directory paths in par2 files
using '/' as the path separator instead of '\' (as per the Par 2.0
specification document). Note: directory paths are stored only when
the '-d' switch is used.

 merged the sources from the CPU-only and CPU/GPU versions so that
both versions now build from the same set of source files using
different 'configure' options (Mac, Linux, FreeBSD) or project files
(Windows). See the source distribution's README_FIRST.txt for building
instructions.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -725,6 +725,8 @@ PLATFORM_DARWIN_TRUE
 PLATFORM_DARWIN_FALSE
 PLATFORM_FREEBSD_TRUE
 PLATFORM_FREEBSD_FALSE
+GPGPU_CUDA_TRUE
+GPGPU_CUDA_FALSE
 CPP
 GREP
 EGREP
@@ -4111,7 +4113,7 @@ _ACEOF
 
 
 case "$host_cpu" in
-	x86_64)
+	x86_64|amd64)
 		{ echo "$as_me:$LINENO: result: SSE2_on_x86_64 is enabled" >&5
 echo "${ECHO_T}SSE2_on_x86_64 is enabled" >&6; }
 		 if true; then
@@ -4455,6 +4457,9 @@ else
 fi
 
 
+cat >>confdefs.h <<\_ACEOF
+#define PLATFORM_LINUX 1
+_ACEOF
 
 		;;
 	*-*-darwin*)
@@ -4484,6 +4489,9 @@ else
 fi
 
 
+cat >>confdefs.h <<\_ACEOF
+#define PLATFORM_DARWIN 1
+_ACEOF
 
 		;;
 	*-*-freebsd*)
@@ -4510,6 +4518,39 @@ fi
 else
   PLATFORM_FREEBSD_TRUE='#'
   PLATFORM_FREEBSD_FALSE=
+fi
+
+
+cat >>confdefs.h <<\_ACEOF
+#define PLATFORM_FREEBSD 1
+_ACEOF
+
+		;;
+esac
+
+case "$gpgpu" in
+	cuda)
+		 if true; then
+  GPGPU_CUDA_TRUE=
+  GPGPU_CUDA_FALSE='#'
+else
+  GPGPU_CUDA_TRUE='#'
+  GPGPU_CUDA_FALSE=
+fi
+
+
+cat >>confdefs.h <<\_ACEOF
+#define GPGPU_CUDA 1
+_ACEOF
+
+		;;
+	*)
+		 if false; then
+  GPGPU_CUDA_TRUE=
+  GPGPU_CUDA_FALSE='#'
+else
+  GPGPU_CUDA_TRUE='#'
+  GPGPU_CUDA_FALSE=
 fi
 
 
@@ -7905,6 +7946,20 @@ echo "$as_me: error: conditional \"PLATFORM_FREEBSD\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${GPGPU_CUDA_TRUE}" && test -z "${GPGPU_CUDA_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"GPGPU_CUDA\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"GPGPU_CUDA\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${GPGPU_CUDA_TRUE}" && test -z "${GPGPU_CUDA_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"GPGPU_CUDA\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"GPGPU_CUDA\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
@@ -8589,6 +8644,8 @@ PLATFORM_DARWIN_TRUE!$PLATFORM_DARWIN_TRUE$ac_delim
 PLATFORM_DARWIN_FALSE!$PLATFORM_DARWIN_FALSE$ac_delim
 PLATFORM_FREEBSD_TRUE!$PLATFORM_FREEBSD_TRUE$ac_delim
 PLATFORM_FREEBSD_FALSE!$PLATFORM_FREEBSD_FALSE$ac_delim
+GPGPU_CUDA_TRUE!$GPGPU_CUDA_TRUE$ac_delim
+GPGPU_CUDA_FALSE!$GPGPU_CUDA_FALSE$ac_delim
 CPP!$CPP$ac_delim
 GREP!$GREP$ac_delim
 EGREP!$EGREP$ac_delim
@@ -8596,7 +8653,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 18; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 20; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
